package migrations

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func DiscoverMigrations(appDir string) ([]MigrationInfo, error) {
	migrationsDir := filepath.Join(appDir, "migrations")

	entries, err := os.ReadDir(migrationsDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("migrations: cannot read directory %s: %w", migrationsDir, err)
	}

	var infos []MigrationInfo
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}

		name := strings.TrimSuffix(entry.Name(), ".go")
		if strings.HasPrefix(name, "_") || strings.HasPrefix(name, ".") {
			continue
		}
		if name == "init" || name == "doc" {
			continue
		}

		parts := strings.SplitN(name, "_", 2)
		if len(parts) != 2 {
			continue
		}

		number, err := strconv.Atoi(parts[0])
		if err != nil {
			continue
		}

		infos = append(infos, MigrationInfo{
			Number:    number,
			Name:     name,
			FileName: entry.Name(),
			FilePath: filepath.Join(migrationsDir, entry.Name()),
		})
	}

	sort.Slice(infos, func(i, j int) bool {
		return infos[i].Number < infos[j].Number
	})

	return infos, nil
}

func NextMigrationNumber(appDir string) (int, error) {
	existing, err := DiscoverMigrations(appDir)
	if err != nil {
		return 1, err
	}

	if len(existing) == 0 {
		return 1, nil
	}

	return existing[len(existing)-1].Number + 1, nil
}

func LastMigrationNumber(appDir string) (int, error) {
	existing, err := DiscoverMigrations(appDir)
	if err != nil {
		return 0, err
	}

	if len(existing) == 0 {
		return 0, nil
	}

	return existing[len(existing)-1].Number, nil
}

type MigrationInfo struct {
	Number   int
	Name    string
	FileName string
	FilePath string
}

func MigrationFilePath(appDir, name string) string {
	return filepath.Join(appDir, "migrations", name+".go")
}

func EnsureMigrationsDir(appDir string) error {
	migrationsDir := filepath.Join(appDir, "migrations")
	if _, err := os.Stat(migrationsDir); os.IsNotExist(err) {
		if err := os.MkdirAll(migrationsDir, 0755); err != nil {
			return fmt.Errorf("migrations: cannot create directory %s: %w", migrationsDir, err)
		}
	}

	initFile := filepath.Join(migrationsDir, "0000_init.go")
	if _, err := os.Stat(initFile); os.IsNotExist(err) {
		content := `// Code generated by jango. DO NOT EDIT.
package migrations
`
		if err := os.WriteFile(initFile, []byte(content), 0644); err != nil {
			return fmt.Errorf("migrations: cannot write init file: %w", err)
		}
	}

	return nil
}