package migrations

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/iMerica/jango/orm"
)

func MakeMigrations(appLabel, appDir string) (string, error) {
	if err := EnsureMigrationsDir(appDir); err != nil {
		return "", err
	}

	beforeState := BuildProjectStateFromMigrations(appLabel)
	afterState := ProjectStateFromRegistry()

	detector := NewAutoDetector(appLabel, beforeState, afterState)
	operations, err := detector.Detect()
	if err != nil {
		return "", fmt.Errorf("migrations: autodetect error: %w", err)
	}

	if len(operations) == 0 {
		return "", nil
	}

	number, err := NextMigrationNumber(appDir)
	if err != nil {
		return "", err
	}

	name := suggestMigrationName(operations)
	migrationName := fmt.Sprintf("%04d_%s", number, name)

	m := Migration{
		AppLabel:     appLabel,
		Name:         migrationName,
		Dependencies: suggestDependencies(appLabel),
		Operations:   operations,
	}

	if number == 1 {
		m.IsInitial = true
	}

	filePath := MigrationFilePath(appDir, migrationName)

	code, err := GenerateMigrationCode(m)
	if err != nil {
		return "", fmt.Errorf("migrations: code generation error: %w", err)
	}

	fileDir := filepath.Dir(filePath)
	if err := os.MkdirAll(fileDir, 0755); err != nil {
		return "", fmt.Errorf("migrations: cannot create directory %s: %w", fileDir, err)
	}

	if err := os.WriteFile(filePath, []byte(code), 0644); err != nil {
		return "", fmt.Errorf("migrations: cannot write migration file %s: %w", filePath, err)
	}

	return migrationName, nil
}

func suggestMigrationName(ops []Operation) string {
	for _, op := range ops {
		switch o := op.(type) {
		case *CreateModel:
			return "initial"
		case *AddField:
			return fmt.Sprintf("add_%s_to_%s", strings.ToLower(o.FieldName), strings.ToLower(o.ModelName))
		case *RemoveField:
			return fmt.Sprintf("remove_%s_from_%s", strings.ToLower(o.FieldName), strings.ToLower(o.ModelName))
		case *AlterField:
			return fmt.Sprintf("alter_%s_on_%s", strings.ToLower(o.FieldName), strings.ToLower(o.ModelName))
		case *DeleteModel:
			return fmt.Sprintf("delete_%s", strings.ToLower(o.Name))
		}
	}
	return "auto"
}

func suggestDependencies(appLabel string) []Dependency {
	existing := GetMigrationsForApp(appLabel)
	if len(existing) == 0 {
		return nil
	}

	sort.Slice(existing, func(i, j int) bool {
		return existing[i].Name < existing[j].Name
	})

	last := existing[len(existing)-1]
	return []Dependency{
		{AppLabel: appLabel, Name: last.Name},
	}
}

func GenerateMigrationCode(m Migration) (string, error) {
	var b strings.Builder

	b.WriteString("// Code generated by jango makemigrations. DO NOT EDIT.\n")
	b.WriteString("// Source: ")
	b.WriteString(m.AppLabel)
	b.WriteString(", Name: ")
	b.WriteString(m.Name)
	b.WriteString("\n\n")

	b.WriteString("package migrations\n\n")

	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/iMerica/jango/migrations\"\n")

	hasOrmImports := false
	for _, op := range m.Operations {
		if needsOrmImport(op) {
			hasOrmImports = true
			break
		}
	}
	if hasOrmImports {
		b.WriteString("\t\"github.com/iMerica/jango/orm\"\n")
	}
	b.WriteString(")\n\n")

	b.WriteString("func init() {\n")
	b.WriteString("\tmigrations.RegisterMigration(migrations.Migration{\n")
	b.WriteString(fmt.Sprintf("\t\tAppLabel:     %q,\n", m.AppLabel))
	b.WriteString(fmt.Sprintf("\t\tName:         %q,\n", m.Name))

	if m.IsInitial {
		b.WriteString("\t\tIsInitial:    true,\n")
	}

	if len(m.Dependencies) > 0 {
		b.WriteString("\t\tDependencies: []migrations.Dependency{\n")
		for _, dep := range m.Dependencies {
			b.WriteString(fmt.Sprintf("\t\t\t{AppLabel: %q, Name: %q},\n", dep.AppLabel, dep.Name))
		}
		b.WriteString("\t\t},\n")
	}

	b.WriteString("\t\tOperations: []migrations.Operation{\n")
	for _, op := range m.Operations {
		code, err := generateOperationCode(op, m.AppLabel)
		if err != nil {
			return "", err
		}
		b.WriteString(code)
		b.WriteString(",\n")
	}
	b.WriteString("\t\t},\n")

	b.WriteString("\t})\n")
	b.WriteString("}\n")

	return b.String(), nil
}

func needsOrmImport(op Operation) bool {
	switch o := op.(type) {
	case *CreateModel:
		return true
	case *AddField:
		return true
	case *RemoveField:
		return true
	case *AlterField:
		return true
	case *RenameField:
		return false
	case *AddIndex:
		return true
	case *RemoveIndex:
		return true
	case *AddConstraint:
		return true
	case *RemoveConstraint:
		return true
	case *AlterModelTable:
		return false
	case *AlterModelOptions:
		return false
	case *RenameModel:
		return false
	case *RunPython:
		return false
	case *RunSQL:
		return false
	case *SeparateDatabaseAndState:
		for _, sop := range o.StateOperations {
			if needsOrmImport(sop) {
				return true
			}
		}
		for _, dop := range o.DatabaseOperations {
			if needsOrmImport(dop) {
				return true
			}
		}
		return false
	default:
		return false
	}
}

func generateOperationCode(op Operation, appLabel string) (string, error) {
	switch o := op.(type) {
	case *CreateModel:
		return generateCreateModelCode(o, appLabel)
	case *DeleteModel:
		return fmt.Sprintf("\t\t\t&migrations.DeleteModel{Name: %q, TableName: %q}", o.Name, o.TableName), nil
	case *AddField:
		return fmt.Sprintf("\t\t\t&migrations.AddField{ModelName: %q, FieldName: %q, Field: %s}",
			o.ModelName, o.FieldName, generateFieldCode(o.Field)), nil
	case *RemoveField:
		return fmt.Sprintf("\t\t\t&migrations.RemoveField{ModelName: %q, FieldName: %q, Field: %s}",
			o.ModelName, o.FieldName, generateFieldCode(o.Field)), nil
	case *AlterField:
		return fmt.Sprintf("\t\t\t&migrations.AlterField{ModelName: %q, FieldName: %q, OldField: %s, NewField: %s}",
			o.ModelName, o.FieldName, generateFieldCode(o.OldField), generateFieldCode(o.NewField)), nil
	case *RenameField:
		return fmt.Sprintf("\t\t\t&migrations.RenameField{ModelName: %q, OldName: %q, NewName: %q}",
			o.ModelName, o.OldName, o.NewName), nil
	case *AddIndex:
		return fmt.Sprintf("\t\t\t&migrations.AddIndex{ModelName: %q, Index: %s}",
			o.ModelName, generateIndexCode(o.Index)), nil
	case *RemoveIndex:
		return fmt.Sprintf("\t\t\t&migrations.RemoveIndex{ModelName: %q, Index: %s}",
			o.ModelName, generateIndexCode(o.Index)), nil
	case *AddConstraint:
		return fmt.Sprintf("\t\t\t&migrations.AddConstraint{ModelName: %q, Constraint: %s}",
			o.ModelName, generateConstraintCode(o.Constraint)), nil
	case *RemoveConstraint:
		return fmt.Sprintf("\t\t\t&migrations.RemoveConstraint{ModelName: %q, Constraint: %s}",
			o.ModelName, generateConstraintCode(o.Constraint)), nil
	case *AlterModelTable:
		return fmt.Sprintf("\t\t\t&migrations.AlterModelTable{ModelName: %q, OldTable: %q, NewTable: %q}",
			o.ModelName, o.OldTable, o.NewTable), nil
	case *AlterModelOptions:
		return fmt.Sprintf("\t\t\t&migrations.AlterModelOptions{ModelName: %q}", o.ModelName), nil
	case *RenameModel:
		return fmt.Sprintf("\t\t\t&migrations.RenameModel{OldName: %q, NewName: %q, OldTable: %q, NewTable: %q}",
			o.OldName, o.NewName, o.OldTable, o.NewTable), nil
	default:
		return fmt.Sprintf("\t\t\t// TODO: unsupported operation: %T", op), nil
	}
}

func generateCreateModelCode(op *CreateModel, appLabel string) (string, error) {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("\t\t\t&migrations.CreateModel{\n"))
	b.WriteString(fmt.Sprintf("\t\t\t\tName:       %q,\n", op.Name))
	b.WriteString(fmt.Sprintf("\t\t\t\tTableName:  %q,\n", op.TableName))

	if op.PKField != "" {
		b.WriteString(fmt.Sprintf("\t\t\t\tPKField:    %q,\n", op.PKField))
	}

	b.WriteString("\t\t\t\tFields: []orm.FieldDef{\n")
	for _, f := range op.Fields {
		b.WriteString(fmt.Sprintf("\t\t\t\t\t%s,\n", generateFieldCode(f)))
	}
	b.WriteString("\t\t\t\t},\n")

	if len(op.Indexes) > 0 {
		b.WriteString("\t\t\t\tIndexes: []orm.IndexDef{\n")
		for _, idx := range op.Indexes {
			b.WriteString(fmt.Sprintf("\t\t\t\t\t%s,\n", generateIndexCode(idx)))
		}
		b.WriteString("\t\t\t\t},\n")
	}

	if len(op.Constraints) > 0 {
		b.WriteString("\t\t\t\tConstraints: []orm.ConstraintDef{\n")
		for _, c := range op.Constraints {
			b.WriteString(fmt.Sprintf("\t\t\t\t\t%s,\n", generateConstraintCode(c)))
		}
		b.WriteString("\t\t\t\t},\n")
	}

	b.WriteString("\t\t\t}")
	return b.String(), nil
}

func generateFieldCode(f orm.FieldDef) string {
	var opts []string

	switch f.FieldType {
	case orm.AutoFieldType:
		return fmt.Sprintf("orm.AutoField(%q)", f.Name)
	case orm.BigAutoFieldType:
		return fmt.Sprintf("orm.BigAutoField(%q)", f.Name)
	case orm.SmallAutoFieldType:
		return fmt.Sprintf("orm.SmallAutoField(%q)", f.Name)
	case orm.CharFieldType:
		opts = appendFieldTypeOptions(f)
		return fmt.Sprintf("orm.CharField(%q, %d%s)", f.Name, f.MaxLength, formatOpts(opts))
	case orm.TextFieldType:
		opts = appendFieldTypeOptions(f)
		return fmt.Sprintf("orm.TextField(%q%s)", f.Name, formatOpts(opts))
	case orm.SlugFieldType:
		opts = appendFieldTypeOptions(f)
		return fmt.Sprintf("orm.SlugField(%q, %d%s)", f.Name, f.MaxLength, formatOpts(opts))
	case orm.EmailFieldType:
		opts = appendFieldTypeOptions(f)
		return fmt.Sprintf("orm.EmailField(%q, %d%s)", f.Name, f.MaxLength, formatOpts(opts))
	case orm.URLFieldType:
		opts = appendFieldTypeOptions(f)
		return fmt.Sprintf("orm.URLField(%q, %d%s)", f.Name, f.MaxLength, formatOpts(opts))
	case orm.UUIDFieldType:
		opts = appendFieldTypeOptions(f)
		return fmt.Sprintf("orm.UUIDField(%q%s)", f.Name, formatOpts(opts))
	case orm.IntFieldType:
		opts = appendFieldTypeOptions(f)
		return fmt.Sprintf("orm.IntegerField(%q%s)", f.Name, formatOpts(opts))
	case orm.BigIntFieldType:
		opts = appendFieldTypeOptions(f)
		return fmt.Sprintf("orm.BigIntegerField(%q%s)", f.Name, formatOpts(opts))
	case orm.SmallIntFieldType:
		opts = appendFieldTypeOptions(f)
		return fmt.Sprintf("orm.SmallIntegerField(%q%s)", f.Name, formatOpts(opts))
	case orm.PositiveIntFieldType:
		opts = appendFieldTypeOptions(f)
		return fmt.Sprintf("orm.PositiveIntegerField(%q%s)", f.Name, formatOpts(opts))
	case orm.FloatFieldType:
		opts = appendFieldTypeOptions(f)
		return fmt.Sprintf("orm.FloatField(%q%s)", f.Name, formatOpts(opts))
	case orm.DoubleFieldType:
		opts = appendFieldTypeOptions(f)
		return fmt.Sprintf("orm.DoubleField(%q%s)", f.Name, formatOpts(opts))
	case orm.DecimalFieldType:
		opts = appendFieldTypeOptions(f)
		return fmt.Sprintf("orm.DecimalField(%q, %d, %d%s)", f.Name, f.MaxLength, f.Decimals, formatOpts(opts))
	case orm.BooleanFieldType:
		opts = appendFieldTypeOptions(f)
		return fmt.Sprintf("orm.BooleanField(%q%s)", f.Name, formatOpts(opts))
	case orm.NullBooleanFieldType:
		opts = appendFieldTypeOptions(f)
		return fmt.Sprintf("orm.NullBooleanField(%q%s)", f.Name, formatOpts(opts))
	case orm.DateFieldType:
		opts = appendFieldTypeOptions(f)
		return fmt.Sprintf("orm.DateField(%q%s)", f.Name, formatOpts(opts))
	case orm.DateTimeFieldType:
		opts = appendFieldTypeOptions(f)
		return fmt.Sprintf("orm.DateTimeField(%q%s)", f.Name, formatOpts(opts))
	case orm.ForeignKeyType:
		opts = appendFieldTypeOptions(f)
		return fmt.Sprintf("orm.ForeignKey(%q, %q%s)", f.Name, f.RelatedModel, formatOpts(opts))
	case orm.OneToOneType:
		opts = appendFieldTypeOptions(f)
		return fmt.Sprintf("orm.OneToOneField(%q, %q%s)", f.Name, f.RelatedModel, formatOpts(opts))
	case orm.ManyToManyType:
		opts = appendFieldTypeOptions(f)
		return fmt.Sprintf("orm.ManyToManyField(%q, %q%s)", f.Name, f.RelatedModel, formatOpts(opts))
	case orm.JSONFieldType:
		opts = appendFieldTypeOptions(f)
		return fmt.Sprintf("orm.JSONField(%q%s)", f.Name, formatOpts(opts))
	default:
		opts = appendFieldTypeOptions(f)
		return fmt.Sprintf("orm.TextField(%q%s)", f.Name, formatOpts(opts))
	}
}

func appendFieldTypeOptions(f orm.FieldDef) []string {
	var opts []string

	if f.Nullable {
		opts = append(opts, "orm.WithNullable")
	}
	if f.Unique {
		opts = append(opts, "orm.WithUnique")
	}
	if f.DBColumn != "" {
		opts = append(opts, fmt.Sprintf("orm.WithDBColumn(%q)", f.DBColumn))
	}
	if f.DBIndex {
		opts = append(opts, "orm.WithDBIndex")
	}
	if f.Default != nil {
		opts = append(opts, fmt.Sprintf("orm.WithDefault(%v)", formatDefault(f.Default)))
	}
	if f.PrimaryKey && f.FieldType != orm.AutoFieldType && f.FieldType != orm.BigAutoFieldType && f.FieldType != orm.SmallAutoFieldType {
		// PrimaryKey is set on auto fields by default, skip for others
	}
	if f.VerboseName != "" {
		opts = append(opts, fmt.Sprintf("orm.WithVerboseName(%q)", f.VerboseName))
	}
	if f.AutoNow {
		opts = append(opts, "orm.WithAutoNow")
	}
	if f.AutoNowAdd {
		opts = append(opts, "orm.WithAutoNowAdd")
	}
	if f.RelatedName != "" && f.RelatedName != "+" {
		opts = append(opts, fmt.Sprintf("orm.WithRelatedName(%q)", f.RelatedName))
	}
	if f.OnDelete != "" && f.OnDelete != orm.Cascade {
		opts = append(opts, fmt.Sprintf("orm.WithOnDelete(orm.%s)", formatOnDelete(f.OnDelete)))
	}
	if f.DBConstraint {
		if f.FieldType == orm.ForeignKeyType || f.FieldType == orm.OneToOneType {
			// default, skip
		} else {
			opts = append(opts, "orm.WithDBConstraint(true)")
		}
	}
	if !f.DBConstraint && (f.FieldType == orm.ForeignKeyType || f.FieldType == orm.OneToOneType) {
		opts = append(opts, "orm.WithDBConstraint(false)")
	}
	if f.Through != "" {
		opts = append(opts, fmt.Sprintf("orm.WithThrough(%q)", f.Through))
	}
	if f.HelpText != "" {
		opts = append(opts, fmt.Sprintf("orm.WithHelpText(%q)", f.HelpText))
	}

	return opts
}

func formatOpts(opts []string) string {
	if len(opts) == 0 {
		return ""
	}
	return ", " + strings.Join(opts, ", ")
}

func formatDefault(v interface{}) string {
	switch val := v.(type) {
	case string:
		return fmt.Sprintf("%q", val)
	case int:
		return fmt.Sprintf("%d", val)
	case int64:
		return fmt.Sprintf("int64(%d)", val)
	case float64:
		return fmt.Sprintf("%f", val)
	case bool:
		if val {
			return "true"
		}
		return "false"
	default:
		return fmt.Sprintf("%v", val)
	}
}

func formatOnDelete(od orm.OnDelete) string {
	switch od {
	case orm.Cascade:
		return "Cascade"
	case orm.Protect:
		return "Protect"
	case orm.SetNull:
		return "SetNull"
	case orm.SetDefault:
		return "SetDefault"
	case orm.Set:
		return "Set"
	case orm.DoNothing:
		return "DoNothing"
	case orm.Restrict:
		return "Restrict"
	default:
		return string(od)
	}
}

func generateIndexCode(idx orm.IndexDef) string {
	fieldsStr := make([]string, len(idx.Fields))
	for i, f := range idx.Fields {
		fieldsStr[i] = fmt.Sprintf("%q", f)
	}

	var parts []string
	parts = append(parts, fmt.Sprintf("Name: %q", idx.Name))
	parts = append(parts, fmt.Sprintf("Fields: []string{%s}", strings.Join(fieldsStr, ", ")))
	if idx.Unique {
		parts = append(parts, "Unique: true")
	}
	if idx.Condition != "" {
		parts = append(parts, fmt.Sprintf("Condition: %q", idx.Condition))
	}

	return fmt.Sprintf("orm.IndexDef{%s}", strings.Join(parts, ", "))
}

func generateConstraintCode(c orm.ConstraintDef) string {
	var parts []string
	if c.Name != "" {
		parts = append(parts, fmt.Sprintf("Name: %q", c.Name))
	}
	if len(c.Unique) > 0 {
		uniqueStr := make([]string, len(c.Unique))
		for i, u := range c.Unique {
			uniqueStr[i] = fmt.Sprintf("%q", u)
		}
		parts = append(parts, fmt.Sprintf("Unique: []string{%s}", strings.Join(uniqueStr, ", ")))
	}
	if c.Check != "" {
		parts = append(parts, fmt.Sprintf("Check: %q", c.Check))
	}
	if c.Condition != "" {
		parts = append(parts, fmt.Sprintf("Condition: %q", c.Condition))
	}

	return fmt.Sprintf("orm.ConstraintDef{%s}", strings.Join(parts, ", "))
}
