package codegen

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
)

type RegistryConfig struct {
	ModulePath    string
	ProjectPkg    string
	InstalledApps []AppEntry
	OutputPkg     string
}

type AppEntry struct {
	ImportPath string
	Label      string
	Name       string
}

type ProjectInfo struct {
	ModulePath string
	ProjectDir string
	Apps       []AppEntry
}

func FindProjectInfo(projectDir string) (*ProjectInfo, error) {
	modFile := filepath.Join(projectDir, "go.mod")
	data, err := os.ReadFile(modFile)
	if err != nil {
		return nil, fmt.Errorf("codegen: cannot read go.mod: %w", err)
	}

	modulePath := ""
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "module ") {
			modulePath = strings.TrimPrefix(line, "module ")
			modulePath = strings.TrimSpace(modulePath)
			break
		}
	}
	if modulePath == "" {
		return nil, fmt.Errorf("codegen: cannot determine module path from go.mod")
	}

	apps, err := discoverApps(projectDir, modulePath)
	if err != nil {
		return nil, err
	}

	return &ProjectInfo{
		ModulePath: modulePath,
		ProjectDir: projectDir,
		Apps:       apps,
	}, nil
}

func discoverApps(projectDir, modulePath string) ([]AppEntry, error) {
	var apps []AppEntry

	appsDir := filepath.Join(projectDir, "apps")
	if _, err := os.Stat(appsDir); os.IsNotExist(err) {
		return apps, nil
	}

	entries, err := os.ReadDir(appsDir)
	if err != nil {
		return nil, fmt.Errorf("codegen: cannot read apps directory: %w", err)
	}

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		appDir := filepath.Join(appsDir, entry.Name())

		if !hasGoAppFile(appDir) {
			continue
		}

		apps = append(apps, AppEntry{
			ImportPath: modulePath + "/apps/" + entry.Name(),
			Label:      entry.Name(),
		})
	}

	return apps, nil
}

func hasGoAppFile(dir string) bool {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	hasGo := false
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".go") && !strings.HasSuffix(e.Name(), "_test.go") {
			hasGo = true
			break
		}
	}
	return hasGo
}

var registryTemplate = template.Must(template.New("registry").Parse(`// Code generated by jango codegen. DO NOT EDIT.

package {{.OutputPkg}}

import (
{{range .InstalledApps}}	{{.Label}} "{{.ImportPath}}"
{{end}}	"github.com/iMerica/jango/apps"
	"github.com/iMerica/jango/conf"
)

func init() {
	apps.ResetRegistry()
}

func RegisterInstalledApps() []apps.App {
	return []apps.App{
{{range .InstalledApps}}		{{.Label}}.App,
{{end}}	}
}

func Bootstrap(settings *conf.Settings) (*apps.BootstrapResult, error) {
	return apps.Bootstrap(settings, RegisterInstalledApps())
}
`))

func GenerateRegistry(info *ProjectInfo, outputDir string) error {
	if outputDir == "" {
		outputDir = info.ProjectDir
	}

	outputPkg := derivePackageName(outputDir)

	cfg := RegistryConfig{
		ModulePath:    info.ModulePath,
		ProjectPkg:    info.ModulePath,
		InstalledApps: info.Apps,
		OutputPkg:     outputPkg,
	}

	var buf strings.Builder
	if err := registryTemplate.Execute(&buf, cfg); err != nil {
		return fmt.Errorf("codegen: failed to execute registry template: %w", err)
	}

	outputPath := filepath.Join(outputDir, "zz_generated_registry.go")
	if err := os.WriteFile(outputPath, []byte(buf.String()), 0644); err != nil {
		return fmt.Errorf("codegen: failed to write %s: %w", outputPath, err)
	}

	if _, err := exec.LookPath("gofmt"); err == nil {
		exec.Command("gofmt", "-w", outputPath).Run()
	}

	return nil
}

func derivePackageName(dir string) string {
	goMod := filepath.Join(dir, "go.mod")
	if _, err := os.Stat(goMod); err == nil {
		data, err := os.ReadFile(goMod)
		if err == nil {
			for _, line := range strings.Split(string(data), "\n") {
				line = strings.TrimSpace(line)
				if strings.HasPrefix(line, "module ") {
					modPath := strings.TrimSpace(strings.TrimPrefix(line, "module "))
					parts := strings.Split(modPath, "/")
					return parts[len(parts)-1]
				}
			}
		}
	}
	return strings.ToLower(filepath.Base(dir))
}
